#!/bin/sh

# extracts the path where the 'iat' shell script is located
CURRENTWD=`dirname $0`
# automatically extract all .jar files in all subdirectories
JARS=`find $CURRENTWD -name '*.jar'`
JARPATH=""
DEFAULT_OBJPATH=""

# append the .jar files using ':' to construct a valid classpath
for JAR in $JARS;
do
	JARPATH="$JARPATH:$JAR"
done

# if AT_HOME env var is not defined, set it to the location of this script
if ! [ $AT_HOME ]; then
  AT_HOME=$CURRENTWD
fi

# all top-level directories in the atlib/ subdirectory become available in the lobby
for ROOT in `ls atlib`
do
  DEFAULT_OBJPATH="$ROOT=$AT_HOME/atlib/$ROOT:$DEFAULT_OBJPATH"
done

# invoke the IAT shell via the JVM and:
# - pass the AT_HOME, AT_INIT and AT_OBJECTPATH environment variables to the JVM environment via -D
# - make sure to include all the jar files in the ./lib directory
# - invoke the main IAT class
# - pass any parameters to this script to IAT
# - pipe System.err to the console
java -DAT_HOME=$AT_HOME -DAT_INIT=$AT_HOME/atlib/at/init/init.at -DAT_OBJECTPATH=$AT_OBJECTPATH -DAT_LIBPATH=$DEFAULT_OBJPATH -classpath .:$CLASSPATH:$JARPATH edu.vub.at.IAT "$@" 2> /dev/console
